/**
 * Credits: a slow scroll. Everything here was generated by code, and the
 * game says so plainly.
 */
import { P } from '../../art/palette';
import type { App } from '../app';
import type { Renderer } from '../draw';
import type { Pointer } from '../input';
import type { Scene } from '../scene';
import { ButtonSet } from '../widgets';

const LINES: [string, number][] = [
  ['DOUBLE OUT', P.BRASS_LIT],
  ['', 0],
  ['A single-player darts roguelite.', P.CHALK],
  ['501 down to nothing. Finish on a double.', P.CHALK],
  ['', 0],
  ['COMMENTARY', P.PEWTER],
  ['BARREL - the excitable one', P.CLARET_LIT],
  ['NOCK - the analyst', P.SKY_LIT],
  ['Gerald, third row, unpaid', P.MIST],
  ['', 0],
  ['ART', P.PEWTER],
  ['Every pixel generated by code at build time.', P.CHALK],
  ['Sixteen colours. Nothing drawn by hand.', P.CHALK],
  ['Nothing downloaded. Nothing painted by a machine.', P.CHALK],
  ['', 0],
  ['MUSIC & SOUND', P.PEWTER],
  ['Synthesised live by the Web Audio API.', P.CHALK],
  ['No recordings. The voices are square waves.', P.CHALK],
  ['', 0],
  ['FONTS', P.PEWTER],
  ['Two bitmap faces defined as bit arrays.', P.CHALK],
  ['5x7 for talking. 9x12 for shouting.', P.CHALK],
  ['', 0],
  ['RULES', P.PEWTER],
  ['The folk game of 501, double out,', P.CHALK],
  ['corrupted by chalk until the maths gives up.', P.CHALK],
  ['', 0],
  ['NO', P.PEWTER],
  ['adverts, accounts, timers, purchases,', P.CHALK],
  ['real people, real brands, endless modes.', P.CHALK],
  ['', 0],
  ['The night can be won. When it is, it stops.', P.BRASS_LIT],
  ['', 0],
  ['Thank you for playing.', P.CHALK],
];

export class CreditsScreen implements Scene {
  buttons = new ButtonSet();
  scroll = 0;
  w = 320;
  h = 180;
  keyboardFocus = false;

  constructor(public app: App) {}

  enter(): void {
    this.resize();
    this.scroll = 0;
  }

  resize(): void {
    this.w = this.app.screen.width;
    this.h = this.app.screen.height;
    this.buttons.clear();
    this.buttons.add({ id: 'back', rect: { x: this.w - 60, y: this.h - 20, w: 56, h: 16 }, label: 'BACK', primary: true, onPress: () => this.app.toTitle() });
    this.buttons.focusFirst();
  }

  onDown(p: Pointer): void {
    this.buttons.down(p.x, p.y);
  }

  onUp(p: Pointer): void {
    this.buttons.up(p.x, p.y);
  }

  onMove(p: Pointer): void {
    this.buttons.move(p.x, p.y);
  }

  onKey(key: string): void {
    if (key === 'Escape') {
      this.app.toTitle();
      return;
    }
    if (this.buttons.key(key)) this.keyboardFocus = true;
  }

  onWheel(dy: number): void {
    this.scroll += dy * 12;
  }

  update(dt: number): void {
    this.scroll += dt * 9;
    const total = LINES.length * 10 + this.h;
    if (this.scroll > total) this.scroll = -20;
  }

  draw(r: Renderer): void {
    r.clear(P.DEEP);
    r.sprite('wall', this.w >= 320 ? 0 : -70, 0);
    r.dither(0, 0, this.w, this.h, P.INK, 8);
    const cx = Math.floor(this.w / 2);
    LINES.forEach((line, i) => {
      const y = Math.round(this.h - this.scroll + i * 10);
      if (y < -10 || y > this.h) return;
      if (!line[0]) return;
      r.text(line[0], cx, y, { color: line[1], align: 'center', shadow: P.INK, scale: i === 0 ? 2 : 1 });
    });
    this.buttons.draw(r, this.keyboardFocus);
  }
}
